// const tasks = [
//   {
//     id: 1,
//     title: "Morbi ut odio.",
//     date: "Wednesday 04 Aug",
//     type: "on-site",
//     time: "evening",
//     place: "VI, LA",
//     assigned: "open",
//     offers: 7,
//     price: 130,
//   },
//   {
//     id: 2,
//     title: "In est risus, auctor sed, tristique in, tempus sit amet, sem.",
//     date: "Wednesday 01 Oct",
//     type: "on-site",
//     time: "afternoon",
//     place: "VI, LA",
//     assigned: "completed",
//     offers: 10,
//     price: 165,
//   },
//   {
//     id: 3,
//     title:
//       "Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.",
//     date: "Wednesday 19 Jun",
//     type: "on-site",
//     time: "morning",
//     place: "Lekki, LA",

//     assigned: "open",
//     offers: 13,
//     price: 31,
//   },
//   {
//     id: 4,
//     title: "Nulla tellus.",
//     date: "Thursday 09 Jun",
//     type: "remote",
//     time: "mid-day",
//     place: "Gwagwalada ,Abj",
//     assigned: "completed",
//     offers: 10,
//     price: 114,
//   },
//   {
//     id: 5,
//     title: "Mauris sit amet eros.",
//     date: "Monday 09 May",
//     type: "on-site",
//     time: "mid-day",
//     place: "Lekki, LA",
//     assigned: "completed",
//     offers: 4,
//     price: 67,
//   },
//   {
//     id: 6,
//     title: "In est risus, auctor sed, tristique in, tempus sit amet, sem.",
//     date: "Friday 9 Apr",
//     type: "remote",
//     time: "evening",
//     place: "Gwagwalada ,Abj",
//     assigned: "open",
//     offers: 13,
//     price: 104,
//   },
//   {
//     id: 7,
//     title:
//       "Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.",
//     date: "Wednesday 9 Jun",
//     type: "remote",
//     time: "evening",
//     place: "Yaba, LA",
//     assigned: "cancelled",
//     offers: 4,
//     price: 31,
//   },
//   {
//     id: 8,
//     title:
//       "Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.",
//     date: "Wednesday 9 Jul",
//     type: "on-site",
//     time: "afternoon",
//     place: "Lekki, LA",
//     assigned: "completed",
//     offers: 11,
//     price: 84,
//   },
//   {
//     id: 9,
//     title: "Morbi ut odio.",
//     date: "Wednesday 9 Jun",
//     type: "remote",
//     time: "morning",
//     place: "Lekki, LA",
//     assigned: "completed",
//     offers: 14,
//     price: 130,
//   },
//   {
//     id: 10,
//     title:
//       "Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.",
//     date: "Tuesday 9 Sep",
//     type: "on-site",
//     time: "afternoon",
//     place: "Gwagwalada ,Abj",
//     assigned: "completed",
//     offers: 3,
//     price: 114,
//   },
// ];
